name: '[QE] Cypress Runner'

on:
  push:
    branches:
      - test/cypress-v9.6.0

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  Cypress:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout App
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Cypress Runner
        run: git clone https://github.com/vtex-apps/cy-runner.git

      - name: Cache
        uses: actions/cache@v2
        with:
          path: '~/.cache/'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Cypress
        run: |
          git checkout test/cypress-v9.6.0
          rm -rf .git
          yarn install --frozen-lockfile
        working-directory: ./cy-runner

      - name: Run Cypress Runner
        run: yarn cy-r
        env:
          VTEX_QE: ${{ secrets.VTEX_QE }}
          NODE_NO_WARNINGS: 1
          NO_COLORS: 1

      - name: Save results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: cy-runner-logs
          path: cy-runner/logs
          retention-days: 3
